affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 50
grid_eps: 0.02
grid_range:
- 0
- 10
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 2
symbolic.funs_name.0:
- - sin
- - sin
- - '0'
- - '0'
- - '0'
- - '0'
symbolic.funs_name.1:
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
symbolic_enabled: true
width:
- - 1
  - 0
- - 6
  - 0
- - 1
  - 0
